version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: laravel-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  node:
    image: node:20-alpine
    container_name: laravel-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-queue
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "php artisan queue:work --verbose --tries=3 --timeout=90"
    depends_on:
      - db
      - redis

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-scheduler
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "php artisan schedule:work"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-mailhog
    ports:
      - "8025:8025"

volumes:
  mysql_data:
